destination: ./_site
server:      true
auto:        true
lsi:         false
server_port: 5000
pygments:    true
markdown:    redcloth
#permalink:   date
permalink:   pretty
paginate:    10
plugins:     ./_plugins